Feature/lendind protocol details
interest-protocol/sui-interface pull request #323
Opened 2023-05-27 18:26 UTC by KipandaJr

2023-05-28 20:48 UTC, okusindja approved these changes

2023-05-28 22:00 UTC, git-marcopitra requested changes

2023-05-28 23:53 UTC, git-marcopitra approved these changes
Check Comments

2023-05-28 23:53 UTC, git-marcopitra commented on components/svg/done.tsx
> +  const { dark } = useTheme() as { dark: boolean };
`useTheme() as Theme;`

2023-05-28 23:53 UTC, git-marcopitra requested changes
Check Comments

2023-05-29 00:01 UTC, git-marcopitra approved these changes

2023-05-29 00:01 UTC, merged