✨ new connect page
interest-protocol/sui-interface pull request #360
Opened 2023-06-27 02:54 UTC by okusindja

- 💫 feat: add illustration and animation
- 🔥 chore: remove unused files

2023-07-27 23:08 UTC, okusindja commented on views/dapp/v2/components/layout/connect-wallet/wallet/wallet-list-section.tsx
> +  'data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iNzIiIGhlaWdodD0iNzIiIHZpZXdCb3g9IjAgMCA3MiA3MiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj4KPHJlY3Qgd2lkdGg9IjcyIiBoZWlnaHQ9IjcyIiByeD
add to constants or as a separated file

2023-07-27 23:29 UTC, okusindja reviewed
approved @KipandaJr

2023-07-28 00:22 UTC, git-marcopitra requested changes

2023-07-28 00:22 UTC, git-marcopitra commented on assets/messages/connect-wallet/en-US.json
Move it to common

2023-07-28 00:22 UTC, git-marcopitra commented on assets/messages/connect-wallet/es-ES.json
Move it to common

2023-07-28 00:22 UTC, git-marcopitra commented on assets/messages/connect-wallet/pt-BR.json
Move it to common

2023-07-28 00:22 UTC, git-marcopitra commented on assets/messages/connect-wallet/pt-PT.json
Move it to common

2023-07-28 00:22 UTC, git-marcopitra commented on interface/declaration.d.ts
We don't need these changes

2023-07-28 00:22 UTC, git-marcopitra commented on pages/dapp/alpha/faucet/index.tsx
Revert these changes

2023-07-28 00:22 UTC, git-marcopitra commented on pages/dapp/alpha/lending/index.tsx
Revert these changes

2023-07-28 00:22 UTC, git-marcopitra commented on pages/dapp/dex/pool/details.tsx
Revert these changes

2023-07-28 00:22 UTC, git-marcopitra commented on pages/dapp/dex/pool/find.tsx
Revert these changes

2023-07-28 00:22 UTC, git-marcopitra commented on pages/dapp/dex/pool/index.tsx
Revert these changes

2023-07-28 00:22 UTC, git-marcopitra commented on pages/dapp/create-token/index.tsx
Revert the connect wallet changes

2023-07-28 00:22 UTC, git-marcopitra commented on pages/dapp/farms/details.tsx
Revert the changes

2023-07-28 00:22 UTC, git-marcopitra commented on pages/dapp/farms/index.tsx
Revert the changes

2023-07-28 00:22 UTC, git-marcopitra commented on pages/dapp/liquidity/details.tsx
Revert the changes

2023-07-28 00:22 UTC, git-marcopitra commented on pages/dapp/liquidity/index.tsx
Revert the changes

2023-07-28 00:22 UTC, git-marcopitra commented on pages/dapp/swap/index.tsx
Revert the changes

2023-07-28 00:22 UTC, git-marcopitra commented on views/dapp/v2/components/layout/connect-wallet/illustration/illustration-section.tsx
> +  const menuVariants = {
Keep this constant outside the component, to not be rendered all the time again

2023-07-28 00:22 UTC, git-marcopitra commented on views/dapp/v2/components/layout/connect-wallet/illustration/illustration-section.tsx
> +      width={['100%', '100%', '100%', '50%']}
why 100% if u are not using others displays? just put it all as 50%

2023-07-28 00:22 UTC, git-marcopitra commented on views/dapp/v2/components/layout/connect-wallet/illustration/illustration.tsx
> +  return (
remove the return

2023-07-28 00:22 UTC, git-marcopitra commented on views/dapp/v2/components/layout/connect-wallet/wallet/wallet-item.tsx
> +  return (
remove the return

2023-07-28 00:22 UTC, git-marcopitra commented on views/dapp/v2/components/layout/connect-wallet/wallet/wallet-list-section.tsx
> +  const menuVariants = {
keep it outsite

2023-07-28 00:22 UTC, git-marcopitra commented on views/dapp/v2/components/layout/wallet/wallet.types.ts
> +export type WalletConnectProps = WalletProps;
Remove this type

2023-08-02 14:16 UTC, git-marcopitra requested changes

2023-08-06 08:32 UTC, merged